Add Git LFS
containerbase/buildpack pull request #15
Opened 2021-04-07 03:14 UTC by fgblomqvist

This adds Git LFS as a tool.
I'm not too sure what kinds of tests you'd expect/want? Or where to add the `install-tool` line. It seems like by default, only git is installed in this base image?

Finally, worth noting is the discussion in https://github.com/renovatebot/renovate/issues/7894.

2021-04-07 05:38 UTC, viceice requested changes
Please checkout other tools like `dotnet` for download and extract tools

https://github.com/containerbase/buildpack/blob/4ca3c834bb5e96ecd0625d450a833365ffaaf686/src/usr/local/buildpack/tools/dotnet.sh#L1-L44

It should be installed to base image after git here:
https://github.com/containerbase/buildpack/blob/8717a2dd66724f98ed8b35f21cc52151885669a3/Dockerfile#L30-L31

and here:
https://github.com/containerbase/buildpack/blob/c0b1b2e6f1b3dc190f841777ce1102c9f3f919c2/Dockerfile.bionic#L27-L28

2021-04-07 05:41 UTC, rarkins commented
@viceice I was thinking we wouldn't want it in the base image (that all images share) and instead only in Renovate?

2021-04-07 05:47 UTC, viceice commented
> @viceice I was thinking we wouldn't want it in the base image (that all images share) and instead only in Renovate?

Ok, so it should be installed to `Dockerfile.bionic` and `test/latest/Dockerfile`  for testing.
We need to prepare a simple git test repo with one lfs file and unse it in tests to verify it works for `root` and `user`

2021-04-07 15:51 UTC, fgblomqvist commented
Found this: https://github.com/git-lfs/git-lfs/wiki/Installation#debian-and-ubuntu
It's essentially possible to install git-lfs and get the latest version from apt if we want. Up to you if you still prefer the tarball for speed.

2021-04-07 15:58 UTC, viceice commented
Please stay at tarball, so we have control over installed version

2021-04-20 00:12 UTC, fgblomqvist commented
Made some changes to the install script, to more-so mimmick the dotnet one you linked @viceice.
The questions that remain are:
* How do we wanna test this?
* What do we do about `git lfs install`? Right now, I install git-lfs by running the install script, which automatically runs `git lfs install` as well. However, it's user-specific which means that it only gets installed/setup for root. But yeah, not sure how we wanna go about it (e.g. what if some people using Renovate don't want git lfs?).

2021-05-06 00:49 UTC, fgblomqvist commented
Bump @viceice @rarkins.

2021-05-06 04:29 UTC, rarkins commented
If git lfs is installed by default for the container, does that cause problems for those who don't want it or need it? I had expected not, but perhaps not aware of the edge cases.

2021-05-06 05:21 UTC, viceice commented
i think it's save to install lfs, because lfs hooks are disabled by renovate renovatebot/renovate#9673

But it think we should only have this installed to main renovate image to not have any side effects on sidecar container starting to pull huge lfs objects

2021-05-06 05:23 UTC, viceice requested changes
Please add a test to https://github.com/containerbase/buildpack/blob/main/test/latest/Dockerfile

2021-05-06 05:26 UTC, viceice commented on src/usr/local/buildpack/tools/git-lfs.sh
> +LFS_FILE="git-lfs-linux-amd64-${TOOL_VERSION}.tar.gz"
Make `ARCH` configurable like in 

https://github.com/containerbase/buildpack/blob/52800f94727f582808d8bc4247f380076554b769/src/usr/local/buildpack/tools/php.sh#L29
https://github.com/containerbase/buildpack/blob/52800f94727f582808d8bc4247f380076554b769/src/usr/local/buildpack/tools/php.sh#L56

2021-05-06 05:26 UTC, viceice commented on src/usr/local/buildpack/tools/git-lfs.sh
> +wget "https://github.com/git-lfs/git-lfs/releases/download/${TOOL_VERSION}/${LFS_FILE}"
All other tools are usiing `curl`, why are you using `wget` ?

2021-07-07 03:29 UTC, jtbandes commented
Hi, what's the status of this work? Seems like this is a necessary step to make progress on https://github.com/renovatebot/renovate/issues/6842.

2021-07-07 08:00 UTC, viceice commented
currently blocked by renovatebot/renovate#10748

2021-07-30 08:51 UTC, viceice commented
Superseeded by #104

2021-07-30 08:51 UTC, closed without merging