Fix linking an already installed version of python
containerbase/buildpack pull request #466
Opened 2022-07-30 23:42 UTC by janrotter

While installing an already present version of python with `install-tool`, the linking process fails (if it is called, i.e. if there is a mismatch between the current version and the one to be installed) because the `MAJOR` and `MINOR` env variables are not set and the constructed path is invalid:

```bash
# src/usr/local/buildpack/tools/v2/python.sh
function link_tool () {
  ...
  python_shell_wrapper "${TOOL_NAME}${MAJOR}" "${versioned_tool_path}"
  python_shell_wrapper "${TOOL_NAME}${MAJOR}.${MINOR}" "${versioned_tool_path}"
```

These variables are set by the `check_semver` function, that is called by the `check_tool_requirements` in the `install_v2_tool` (`src/usr/local/buildpack/utils/install.sh`), but that invocation is skipped when the tool is already present and only requires linking.

This change adds a suitable test and the `check_semver` call in the `link_tool` definition for python to address this issue.

2022-07-31 05:09 UTC, viceice requested changes
this only fixes it for python, we need to fix it for all tools

- #462

2022-07-31 07:27 UTC, janrotter commented
Thank you @viceice for a quick response.

Would always calling the `check_tool_requirements` in the `install_v2_tool` be a better solution?
```diff
diff --git a/src/usr/local/buildpack/utils/install.sh b/src/usr/local/buildpack/utils/install.sh
index bdae973..adc34da 100644
--- a/src/usr/local/buildpack/utils/install.sh
+++ b/src/usr/local/buildpack/utils/install.sh
@@ -12,9 +12,10 @@ function install_v2_tool () {
   # shellcheck source=/dev/null
   . "${path}"
 
+  check_tool_requirements
+
   if ! check_tool_installed; then
     echo "installing v2 tool ${TOOL_NAME} v${TOOL_VERSION}"
-    check_tool_requirements
     install_tool
   else
     echo "tool ${TOOL_NAME} v${TOOL_VERSION} is already installed"
```

2022-07-31 07:35 UTC, viceice commented
yes i think so.

@Chumper WDYT?

2022-07-31 09:41 UTC, Chumper commented
Yes, simply add it to the install method, there is no harm in doing that.

2022-08-01 11:14 UTC, viceice approved these changes

2022-08-01 11:16 UTC, rarkins approved these changes

2022-08-01 11:16 UTC, viceice approved these changes

2022-08-01 11:26 UTC, merged