feat(node): use openssl ca certificates
containerbase/buildpack pull request #97
Opened 2021-07-15 15:06 UTC by viceice

closes #61

2021-07-15 15:57 UTC, rarkins requested changes

2021-07-15 15:57 UTC, rarkins commented on docs/custom-root-ca.md
> +We use `NODE_OPTIONS="--use-openssl-ca"`, so NodeJS is using the same certifacte options as OpenSSL.
Typo

2021-07-15 15:58 UTC, rarkins commented
Any easy way to verify it works?

2021-07-15 16:06 UTC, viceice commented on docs/custom-root-ca.md
> +We use `NODE_OPTIONS="--use-openssl-ca"`, so NodeJS is using the same certifacte options as OpenSSL.
```suggestion
We use `NODE_OPTIONS="--use-openssl-ca"`, so NodeJS is using the same certificate options as OpenSSL.
```

2021-07-15 16:06 UTC, viceice commented on test/latest/Dockerfile
> +  nginx && su -c 'SSL_CERT_FILE=/test/ca.pem node request.mjs' ${USER_NAME}
This is the test. Simple https request with a custom root certificate.

2021-07-16 14:39 UTC, rarkins approved these changes

2021-07-16 14:44 UTC, merged